---
title: "R Notebook"
output: html_notebook
---

# DC Exercises: 13.1, 13.2, 16.1, 16.2

## Chapter 13

### 13.1
```{r}
#Loading in BabyNames data set
library(DataComputing)
data("BabyNames")
```

```{r}
#Finding 5 most popular baby names per sex
BabyNames%>%
  group_by(sex)%>%
  na.omit()%>%
  filter(rank(desc(count)) <= 5)%>%
  arrange(sex)
```


### 13.2

#### 1.
```{r}
partA <-
  BabyNames%>%
  group_by(year, name)%>%
  summarise(yrcount = sum(count))%>%
  mutate(nrank = rank(desc(yrcount)), ranking = ifelse(nrank <= 100, "Top_100", "Below"))

partB <-
  partA%>%
  group_by(year, ranking)%>%
  summarise(total = sum(yrcount))%>%
  arrange(desc(year))
partB
```

#### 2.
```{r}
library(tidyr)
fraction <-
  partB %>%
  spread(key = ranking, value = total)%>%
  mutate(Top_Fraction = Top_100/(Top_100 + Below))
fraction
```

#### 3.
```{r}
library(ggplot2)
fraction%>%
  ggplot(aes(x = year, y = Top_Fraction))+
  geom_line()+
  ggtitle("Fraction of Top 100 Names over the Years")
```


#### 2.


## Chapter 16


### 16.1

#### 1.

(A.) using lubridate::mdy()

(B.)
```{r}
library(lubridate)
lubridate::mdy("November 24, 1999") - lubridate::mdy("April 30, 1777")
```


#### 2.

(A.) using lubridate::mdy

(B.)
```{r}
lubridate::mdy("November 24, 1999") - lubridate::mdy("06-23-1912")
```


#### 3.

(A.) using lubridate::dmy

(B.)
```{r}
lubridate::mdy("November 24, 1999") - lubridate::dmy("3 March 1847")
```


#### 4.

(A.) using lubridate::mdy_hm()

(B.)
```{r}
lubridate::mdy_hm("Nov. 24th, 1999 at 12:00 am") - lubridate::mdy_hm("Nov. 11th, 1918 at 11:00 am")
```


#### 5.

(A.) using lubridate::mdy

(B.)
```{r}
lubridate::mdy("November 24, 1999") - lubridate::mdy("July 20, 1969")
```



### 16.2

1. readr::parse_number()

2. readr::parse_number()

3. Neither

4. readr::parse_number()

5. Neither

6. readr::parse_number()

7. readr::parse_number()

8. as.numeric()

9. Neither